apiVersion: v1
kind: Pod
metadata:
  name: httpd
  namespace: secops
spec:
  containers:
    - name: httpd
      image: httpd:alpine

---
apiVersion: v1
kind: Service
metadata:
  name: httpd
  namespace: secops
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
